source 'https://rubygems.org'
ruby '3.0.3'

gem 'coffee-script'
gem 'github-pages'
gem 'pathutil', github: 'https://github.com/envygeeks/pathutil/pull/5'
gem 'webrick'
gem 'puma', '~> 4.3'
gem 'rack-jekyll', '~> 0.5.0', github: 'adaoraul/rack-jekyll'
gem 'rake'
gem 'sass'
